export const transactions = [
  { date: "1st July", name: "Ramesh", amount: 250, description: "Paid for movie tickets" },
  { date: "1st July", name: "Sowmya", amount: 180, description: "Paid for coffee at Starbucks" },
  { date: "2nd July", name: "Venkatesh", amount: 520, description: "Paid in Andhra Mess" },
  { date: "2nd July", name: "Keerthi", amount: 300, description: "Paid for shopping at Lifestyle" },
  { date: "3rd July", name: "Arun", amount: 150, description: "Paid for snacks" },
  { date: "3rd July", name: "Ramesh", amount: 400, description: "Paid for petrol" },
  { date: "4th July", name: "Sowmya", amount: 270, description: "Paid for groceries" },
  { date: "4th July", name: "Venkatesh", amount: 360, description: "Paid for movie tickets" },
  { date: "5th July", name: "Keerthi", amount: 90, description: "Paid for ice cream" },
  { date: "5th July", name: "Arun", amount: 550, description: "Paid in BBQ Nation" },
  { date: "6th July", name: "Ramesh", amount: 130, description: "Paid for breakfast" },
  { date: "6th July", name: "Sowmya", amount: 210, description: "Paid in Saravana Bhavan" },
  { date: "7th July", name: "Venkatesh", amount: 180, description: "Paid for parking" },
  { date: "7th July", name: "Keerthi", amount: 320, description: "Paid for shopping at Pantaloons" },
  { date: "8th July", name: "Arun", amount: 90, description: "Paid for tea and snacks" },
  { date: "8th July", name: "Ramesh", amount: 600, description: "Paid in Paradise Biryani" },
  { date: "9th July", name: "Sowmya", amount: 250, description: "Paid for cab ride" },
  { date: "9th July", name: "Venkatesh", amount: 310, description: "Paid for lunch at Sangeetha" },
  { date: "10th July", name: "Keerthi", amount: 160, description: "Paid for cake at bakery" },
  { date: "10th July", name: "Arun", amount: 230, description: "Paid for internet bill" },
  { date: "11th July", name: "Ramesh", amount: 200, description: "Paid in Udupi hotel" },
  { date: "11th July", name: "Sowmya", amount: 175, description: "Paid for flowers and gifts" },
  { date: "12th July", name: "Venkatesh", amount: 490, description: "Paid for new shirt" },
  { date: "12th July", name: "Keerthi", amount: 220, description: "Paid for tiffin" },
  { date: "13th July", name: "Arun", amount: 180, description: "Paid for chai and samosa" },
  { date: "13th July", name: "Ramesh", amount: 340, description: "Paid in Biryani Blues" },
  { date: "14th July", name: "Sowmya", amount: 280, description: "Paid for haircut" },
  { date: "14th July", name: "Venkatesh", amount: 110, description: "Paid for juice" },
  { date: "15th July", name: "Keerthi", amount: 195, description: "Paid in Veg restaurant" },
  { date: "15th July", name: "Arun", amount: 400, description: "Paid for dinner with friends" },
];
